server_defs:( [] time: `time$();
                 server_id: `$();
                 name: `$();
                 game_type: `$();
                 hostname: `$();
                 game_port: `int$();
                 rcon_port: `int$();
                 query_port: `int$();
                 telnet_port: `int$();
                 web_port: `int$();
                 rcon_pwd: `$();
                 web_pwd: `$();
                 telnet_pwd: `$();
                 deleted: `boolean$());
